### ISSUE TITLE
[BUG/ISSUE] Hard crash on loading/generating world

### ISSUE THREAD

**Issue by jorrit200** [CerbonXD/BetterTotemOfUndying-FABRIC#1] opened 2023-10-02 20:21 UTC
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of Better Totem Of Undying Mod**
- [x] **I have checked the [FAQ](https://github.com/CerbonXD/BetterTotemOfUndying/blob/master/FAQ.md) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/CerbonXD/BetterTotemOfUndying/blob/master/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/CerbonXD/BetterTotemOfUndying/blob/master/CODE_OF_CONDUCT.md)**

## Minecraft Version
1.20.2

## Describe the bug
The game crashes when loading or generating a world.

## To Reproduce
1. Create or load a world
2. Game crashes right before displaying the loading square
3. MC launcher claims the issue is due to an out-of-date graphics driver, or incompatible recording software
4. See stacktrace

## Expected behavior
I want the world to load :(

## Latest Log

<details>

```
---- Minecraft Crash Report ----
// My bad.

Time: 2023-10-02 19:34:04
Description: Starting integrated server

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3324 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.minecraft.class_310.method_29603(class_310.java:2144)
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:270)
	at net.minecraft.class_310.method_29610(class_310.java:2144)
	at net.minecraft.class_7196.method_43326(class_7196.java:255)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:754)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
	at java.base/java.util.concurrent.CompletableFuture.thenAcceptAsync(CompletableFuture.java:2191)
	at net.minecraft.class_7196.method_41899(class_7196.java:253)
	at net.minecraft.class_7196.method_41894(class_7196.java:69)
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:592)
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:482)
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:404)
	at net.minecraft.class_350.method_25402(class_350.java:309)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:99)
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:99)
	at net.minecraft.class_312.method_22686(class_312.java:180)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237)
	at net.minecraft.class_310.method_1523(class_310.java:1300)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 37 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.cardinal_components_entity.json:common.MixinPlayerManager from mod cardinal-components-entity] from phase [DEFAULT] in config [mixins.cardinal_components_entity.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 40 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on onPlayerLogIn could not find any targets matching 'Lnet/minecraft/class_3324;method_14570(Lnet/minecraft/class_2535;Lnet/minecraft/class_3222;)V' in net.minecraft.class_3324. Using refmap cardinal-components-entity-refmap.json [PREINJECT Applicator Phase -> mixins.cardinal_components_entity.json:common.MixinPlayerManager from mod cardinal-components-entity -> Prepare Injections ->  -> handler$zbe000$cardinal-components-entity$onPlayerLogIn(Lnet/minecraft/class_2535;Lnet/minecraft/class_3222;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
	at jdk.internal.reflect.GeneratedConstructorAccessor60.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 40 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.minecraft.class_310.method_29603(class_310.java:2144)
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:270)
	at net.minecraft.class_310.method_29610(class_310.java:2144)
	at net.minecraft.class_7196.method_43326(class_7196.java:255)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:754)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
	at java.base/java.util.concurrent.CompletableFuture.thenAcceptAsync(CompletableFuture.java:2191)
	at net.minecraft.class_7196.method_41899(class_7196.java:253)
	at net.minecraft.class_7196.method_41894(class_7196.java:69)
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:592)
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:482)
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:404)
	at net.minecraft.class_350.method_25402(class_350.java:309)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:99)
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:99)
	at net.minecraft.class_312.method_22686(class_312.java:180)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)

-- Starting integrated server --
Details:
	Level ID: New World (1)
	Level Name: New World
Stacktrace:
	at net.minecraft.class_310.method_29610(class_310.java:2144)
	at net.minecraft.class_7196.method_43326(class_7196.java:255)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:754)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
	at java.base/java.util.concurrent.CompletableFuture.thenAcceptAsync(CompletableFuture.java:2191)
	at net.minecraft.class_7196.method_41899(class_7196.java:253)
	at net.minecraft.class_7196.method_41894(class_7196.java:69)
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:592)
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:482)
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:404)
	at net.minecraft.class_350.method_25402(class_350.java:309)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:99)
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:99)
	at net.minecraft.class_312.method_22686(class_312.java:180)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237)
	at net.minecraft.class_310.method_1523(class_310.java:1300)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2488)
	at net.minecraft.class_310.method_43589(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:845)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 457448120 bytes (436 MiB) / 1329594368 bytes (1268 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i7-12700H
	Identifier: Intel64 Family 6 Model 154 Stepping 3
	Microarchitecture: Alder Lake
	Frequency (GHz): 2.69
	Number of physical packages: 1
	Number of physical CPUs: 14
	Number of logical CPUs: 20
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2520
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3742
	Graphics card CERBON-MODS/CERBONs-Better-Totem-of-Undying-FORGE#1 name: Intel(R) Iris(R) Xe Graphics
	Graphics card CERBON-MODS/CERBONs-Better-Totem-of-Undying-FORGE#1 vendor: Intel Corporation (0x8086)
	Graphics card CERBON-MODS/CERBONs-Better-Totem-of-Undying-FORGE#1 VRAM (MB): 1024.00
	Graphics card CERBON-MODS/CERBONs-Better-Totem-of-Undying-FORGE#1 deviceId: 0x46a6
	Graphics card CERBON-MODS/CERBONs-Better-Totem-of-Undying-FORGE#1 versionInfo: DriverVersion=31.0.101.4146
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 4.80
	Memory slot #0 type: Unknown
	Memory slot CERBON-MODS/CERBONs-Better-Totem-of-Undying-FORGE#1 capacity (MB): 8192.00
	Memory slot CERBON-MODS/CERBONs-Better-Totem-of-Undying-FORGE#1 clockSpeed (GHz): 4.80
	Memory slot CERBON-MODS/CERBONs-Better-Totem-of-Undying-FORGE#1 type: Unknown
	Virtual memory max (MB): 19123.87
	Virtual memory used (MB): 15152.73
	Swap memory total (MB): 3072.00
	Swap memory used (MB): 51.54
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		better_totem_of_undying: Better Totem of Undying [FABRIC] 1.20.1-1.1.0
			cardinal-components-base: Cardinal Components API (base) 5.2.1
			cardinal-components-entity: Cardinal Components API (entities) 5.2.1
		betterallay: Better Allay [FABRIC]-1.4.0-1.20.2
		betterbeaconplacement: Better Beacon Placement 3.1
		bettermounthud: Better Mount HUD 1.2.2
		betterthirdperson: Better Third Person 1.9.0
		blur: Blur (Fabric) 3.1.1
			midnightlib: MidnightLib 1.5.0
			satin: Satin 1.14.0
		bounced: Bounced 3.1.1
		cloth-config: Cloth Config v12 12.0.109
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 6.66
		ctov: ChoiceTheorem's Overhauled Village 3.3.5a
		dismountentity: Dismount Entity 3.0
		do_a_barrel_roll: Do a Barrel Roll 3.3.4+1.20
			cicada: CICADA 0.4.4
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			mixinsquared: MixinSquared 0.1.1
		entity_model_features: Entity Model Features 1.0.2
		entity_texture_features: Entity Texture Features 4.5.1
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		explosiveenhancement: Explosive Enhancement 1.2.1-1.20.x
		fabric-api: Fabric API 0.89.3+1.20.2
			fabric-api-base: Fabric API Base 0.4.33+fce67b32a0
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.41+fce67b32a0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+d9a2869ba0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.12+73761d2ea0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+73761d2ea0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.43+f4b7e424a0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.4+86b12645a0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.36+f71b366fa0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.15+86b12645a0
			fabric-commands-v0: Fabric Commands (v0) 0.2.53+df3654b3a0
			fabric-containers-v0: Fabric Containers (v0) 0.1.72+df3654b3a0
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.4+285022b3a0
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.7+f4b7e424a0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.20+f4b7e424a0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.2+d19c4129a0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.56+b1229956a0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.25+f4b7e424a0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.9+daef22a2a0
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.68+df3654b3a0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+f4b7e424a0
			fabric-item-api-v1: Fabric Item API (v1) 2.1.32+43511215a0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.13+f4b7e424a0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.38+f4b7e424a0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.36+df3654b3a0
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.26+3bafade3a0
			fabric-loot-api-v2: Fabric Loot API (v2) 2.0.2+0ba8e9cea0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.1+e982ae85a0
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.54+f4b7e424a0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.5+f4b7e424a0
			fabric-models-v0: Fabric Models (v0) 0.4.4+9386d8a7a0
			fabric-networking-api-v1: Fabric Networking API (v1) 3.0.8+b18afef3a0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 12.1.1+b1b4f7b0a0
			fabric-particles-v1: Fabric Particles (v1) 1.1.4+f4b7e424a0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.5+96509552a0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.3+34a3e0e2a0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+2034447ca0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+2034447ca0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.48+df3654b3a0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.39+73761d2ea0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.30+f4b7e424a0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.51+df3654b3a0
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.10+86b12645a0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.9+43511215a0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.11+86b12645a0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.11+0ba8e9cea0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.38+86b12645a0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.14+f4b7e424a0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.8+109a65e5a0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.3+fce67b32a0
		fabricloader: Fabric Loader 0.14.22
		fallingleaves: Falling Leaves 1.15.3
		fallingtree: FallingTree 5.0.0
		iris: Iris 1.6.9
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 16.0.0.28
		make_bubbles_pop: Make Bubbles Pop Mod 0.2.0-fabric
		minecraft: Minecraft 1.20.2
		modmenu: Mod Menu 8.0.0
		notenoughanimations: NotEnoughAnimations 1.6.4
		simplehudenhanced: Simple Hud Enhanced v3.1.0
		sodium: Sodium 0.5.3
		structory: Structory 1.3.3
		telepistons: Telepistons 1.1.3
		terrablender: TerraBlender 3.0.0.170
			com_electronwill_night-config_core: core 3.6.4
			com_electronwill_night-config_toml: toml 3.6.4
		visuality: Visuality 0.7.1+1.20
		wakes: Wakes 0.2.0
			blue_endless_jankson: jankson 1.2.2
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	JVM uptime in seconds: 68.985
	Launched Version: fabric-loader-0.14.22-1.20.2
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 537.42, NVIDIA Corporation
	Window size: 1920x1008
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: en_us
	Locale: en_US
	CPU: 20x 12th Gen Intel(R) Core(TM) i7-12700H
```

</details>

## Additional context
Altough the launcher tries to be helpful by telling us the issue is due to an old grapics driver, or recording software, I'm pretty sure this is not the case. I have used multiple versions of my grapics driver, and disabled all recording software (even the sneaky stuff like the xbox gamebar). The error persists.

**Comment by CerbonXD** [comment] 2023-10-03 01:54
Thanks for reporting it. I tested a little bit today and seems to be an issue with the cardinal components API that I'm using in the mod. I will check it tomorrow and see if I can fix it. Also, I'm going to transfer this issue to the Fabric repository of the mod, since the problem is on fabric not forge.

**Comment by jorrit200** [comment] 2023-10-03 16:08
Oh right. My bad, I just clicked on the issue link in CurseForge and didn't check the repo I was on.

**Comment by CerbonXD** [comment] 2023-10-09 14:09
The problem is now fixed. Version (1.1.1). Sorry for the time it took to be fixed, I was kinda busy these days. If you have any other problem please let me know.

**Closed as completed by CerbonXD** 2023-10-09 14:09 UTC
